version: '3.7'

services:
  web_backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    environment:
      PYTHONPATH: '/app/src/'
    volumes:
      - "../log:/app/log"
    command: ["src/bt/wsgi.py",
              "--https-port", "443",
              "--https-only",
              "--server-name", "itman.icu",
              "--ssl-certificate-file", "./letsencrypt/live/itman.icu/cert.pem",
              "--ssl-certificate-key-file", "./letsencrypt/live/itman.icu/privkey.pem",
              "--ssl-certificate-chain-file", "./letsencrypt/live/itman.icu/fullchain.pem",
              # "--ssl-ca-certificate-file", "./letsencrypt/live/itman.icu/cert.pem",
              # "--ssl-verify-client", "/admin/",
              # "--document-root", "/app/static_in_env/",
              # "--url-alias", "/d/", "/app/download/",
              "--port", "8080"]
    ports:
      - "8080:8080"
      - "443:443"
  # https端口只能是443，nginx不能和apache部署在同一台服务器
#  web_static:
#    build:
#      context: ..
#      dockerfile: docker/nginx.dockerfile
#    volumes:
#      - "../assets:/usr/share/nginx/html"
#    ports:
#      # 官方镜像默认暴露80端口
#      # - "80:80"
#      - "443:443"
#    depends_on:
#      - web_backend
